### ISSUE TITLE
[feat] provide environment variable to force color-support

### ISSUE THREAD

**Issue by Delagen** [isaacs/color-support#6]
Have CI that uses gulp.js, but this detects that and disables color-support, but log viewer of CI system supports coloring logs. So need flag to force color-support. (earlier I use FORCE_COLOR)

**Comment by Delagen** [comment]
@isaacs Any news?

**Comment by isaacs** [comment]
`TERM=xterm-256color` would do this.

**Comment by isaacs** [comment]
Or just tell Gulp to give you a way to force color output, even if `color-support` says it shouldn't.
